### ISSUE TITLE
ModuleNotFoundError: No module named 'hivemind_presence'

### ISSUE THREAD

**Issue by goldyfruit** [JarbasHiveMind/HiveMind-voice-sat#22]
```
$ hivemind-voice-sat

2023-06-27 18:03:30.141 - OVOS - ovos_utils.configuration:get_xdg_config_save_path - WARNING - Deprecation version=0.1.0. Caller=ovos_backend_client.identity:61. configuration moved to the `ovos_config` package.
2023-06-27 18:03:30.167 - OVOS - ovos_utils.configuration:get_xdg_base - WARNING - Deprecation version=0.1.0. Caller=ovos_backend_client.identity:62. configuration moved to the `ovos_config` package.
Traceback (most recent call last):
  File "/home/goldyfruit/Virtualenvs/hivemind/bin/hivemind-voice-sat", line 33, in <module>
    sys.exit(load_entry_point('HiveMind-voice-sat==2.0.0a1', 'console_scripts', 'hivemind-voice-sat')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/goldyfruit/Virtualenvs/hivemind/bin/hivemind-voice-sat", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/goldyfruit/Virtualenvs/hivemind/lib64/python3.11/site-packages/hivemind_voice_satellite/__main__.py", line 2, in <module>
    from hivemind_presence import LocalDiscovery
ModuleNotFoundError: No module named 'hivemind_presence'
```

**Comment by goldyfruit** [comment]
Invalid
