### ISSUE TITLE
Doesn't reconnect to the listener

### ISSUE THREAD

**Issue by goldyfruit** [JarbasHiveMind/HiveMind-voice-sat#24]
If the listener restart, the voice-sat is not able to reconnect to it.

```
2023-06-27 19:24:54.665 - OVOS - ovos_bus_client.client.client:on_error:121 - WARNING - Message Bus Client will reconnect in 5.0 seconds.
2023-06-27 19:24:59.774 - OVOS - hivemind_bus_client.client:on_message:148 - WARNING - Message was unencrypted
2023-06-27 19:24:59.784 - OVOS - hivemind_bus_client.protocol:handle_hello:122 - INFO - HELLO: {'pubkey': '-----BEGIN PGP PUBLIC KEY BLOCK-----\n\nxsFNBGSbbwoBEAC0k5PzsGEizC1bRZOE/PstNmnBjZNwvaof8uoijVFZbWwMJzPo\nu+jkLbSW42ejOV3tB97v/mJ8f+yZ0ep/GzwTpjF/JYg+WyCACV1S5Vm2eGHMrCeP\nvVUyjS3U1JjQbK7nisyu6/mPyUMt6bAnc77H7PHBnQTOAcqB5o9BDNoXwSiIdNHR\nS1f3XlZKZiW5fzFoNzj/3t9OIrEI59xHMaLwQJ5tObPi5PDxZTBEWICBPA3Uu1Nu\nrGSCpWvC5pxKeSUEJMmGhioITTe2D7CMQYO2tffoiVYQ3OIzyABahaeSz9xYl0Ot\n4IGWVO1fQzQBP7Pse04YADf+e7fjaqguiFySB3nkFh08U/2hOiAECykqwXW7NEzt\n4Vkhwa446AwJFIKX9vvtJHlGrnyQvayCAJ59MpO9vexpq9Vf+uRTbYEG0zJtqFRY\n25jgF9R+RcLoq0qNfS6pAzkf17IZ2MSXuCn9h4vEpMhGSxKjT+n///5ltnsMGkQ2\nUmext84qMAfgvRqSqJSNnhmhuCxRPqmSa+0lyZymuLJtfzX22cSuuXAKbfTr9Is5\nwmfrSvofyUiQckEZEx/PFv0Wm0+DrHRKNg6E+fXET1/LFoFm5WselGFzGJENxMMq\nXFbswijxjMrtY5c1BHYeOTC0srzzc2hRYQKQjbxv0ILnvgHu5FkxACC+VwARAQAB\nzRBQb29yTWFuSGFuZHNoYWtlwsGGBBMBCgAwBQJkm28LAhsGAwsJDQMVCggEFgMB\nAAIeARYhBMJQOYV/vWoFW7h4vGjN6M/9cJyqAAoJEGjN6M/9cJyqlCIP/3huUDX+\n8sZNcp1UvAzdc+VZIuzVNZ/IBLpzw1xxhneVIVhjFIkZblmjvmuncgnVzXtNqjdj\nrkPNdSzW4hEOqzkxgz2AKrxNuvcxlhcr11OvxoMqukGx5oMoEAjoDdGxE2680o0P\nOioC3P9TXT+7BvjVsXojf8oUAyBzu3DQZiLiqTLEOH/BlYNW3uDnPPKEqeZPTv9e\n/NbLL4cSj360pztmO4OhJzqb1sgLutFfn89ctFZoHfcFLlSV2PM1Biw3DXzCn+im\nsUj3YaGDKkpImpZS01Q1+65IBxbQkKKNBhbwsGWLChRy6bQsTli4/l8KDLqqfW2W\nX3phYeb4+PvjoKY7ERnc8OLFB6nuUACglt7G4EIErCskI/VYXJvHeARNHiLsWp5K\n2NtOvpRgMy+17HMia+7kMFuY1mDOSpu2yLDq/z8aRiZO4vCbab7fJvhdX6kaBFKR\n3I1vVhGWOl+pGVvbr7Thrp9Nr92B6q8CxaUym996VnOLNH7Sk4xC9721HCCP6O0p\nIiLb8reakbKil4T6ymZysz80NECjF8TZCZqnP3+nBGqeLYSrd73mOmcDs9oHBZBx\nSklQ1Xl4tzE24IEksakwvGWZ/CYiD1WILW8JyNfUNeso95Gnu+Mc7Zv1EsdtGK0X\n7l4nKHgW+YW4jgqcrfxpij6dWz92VMvwJ3kX\n=NiKb\n-----END PGP PUBLIC KEY BLOCK-----\n', 'peer': 'VoiceSatelliteV0.3.0:192.168.100.245::206b719e-f2b8-4008-bb5e-5e664ffd9ba1', 'node_id': 'master:0.0.0.0'}
2023-06-27 19:24:59.797 - OVOS - hivemind_bus_client.client:on_message:148 - WARNING - Message was unencrypted
2023-06-27 19:24:59.809 - OVOS - hivemind_bus_client.protocol:handle_handshake:130 - INFO - HANDSHAKE: {'handshake': False, 'min_protocol_version': 0, 'max_protocol_version': 1, 'preshared_key': True, 'password': True, 'crypto_required': True}
2023-06-27 19:24:59.814 - OVOS - hivemind_bus_client.client:emit:186 - INFO - sending to HiveMind: {"msg_type": "shake", "payload": {"envelope": "384e3146445a5777ad02c5419da861575e4c888578ed0563"}, "route": [], "node": null, "source_peer": null}
2023-06-27 19:24:59.841 - OVOS - ovos_bus_client.client.client:on_error:108 - WARNING - Could not send message because connection has closed
2023-06-27 19:24:59.848 - OVOS - ovos_bus_client.client.client:on_error:119 - ERROR - Exception closing websocket at ws://192.168.100.55:5678?authorization=Vm9pY2VTYXRlbGxpdGVWMC4zLjA6MzcyNTdlNWVkMDhkNTg2MDA5NDM0ZGQ4N2I0ODIwMTM=: Connection is already closed.
2023-06-27 19:24:59.854 - OVOS - ovos_bus_client.client.client:on_error:121 - WARNING - Message Bus Client will reconnect in 5.0 seconds.
2023-06-27 19:25:04.967 - OVOS - hivemind_bus_client.client:on_message:148 - WARNING - Message was unencrypted
2023-06-27 19:25:04.974 - OVOS - hivemind_bus_client.protocol:handle_hello:122 - INFO - HELLO: {'pubkey': '-----BEGIN PGP PUBLIC KEY BLOCK-----\n\nxsFNBGSbbwoBEAC0k5PzsGEizC1bRZOE/PstNmnBjZNwvaof8uoijVFZbWwMJzPo\nu+jkLbSW42ejOV3tB97v/mJ8f+yZ0ep/GzwTpjF/JYg+WyCACV1S5Vm2eGHMrCeP\nvVUyjS3U1JjQbK7nisyu6/mPyUMt6bAnc77H7PHBnQTOAcqB5o9BDNoXwSiIdNHR\nS1f3XlZKZiW5fzFoNzj/3t9OIrEI59xHMaLwQJ5tObPi5PDxZTBEWICBPA3Uu1Nu\nrGSCpWvC5pxKeSUEJMmGhioITTe2D7CMQYO2tffoiVYQ3OIzyABahaeSz9xYl0Ot\n4IGWVO1fQzQBP7Pse04YADf+e7fjaqguiFySB3nkFh08U/2hOiAECykqwXW7NEzt\n4Vkhwa446AwJFIKX9vvtJHlGrnyQvayCAJ59MpO9vexpq9Vf+uRTbYEG0zJtqFRY\n25jgF9R+RcLoq0qNfS6pAzkf17IZ2MSXuCn9h4vEpMhGSxKjT+n///5ltnsMGkQ2\nUmext84qMAfgvRqSqJSNnhmhuCxRPqmSa+0lyZymuLJtfzX22cSuuXAKbfTr9Is5\nwmfrSvofyUiQckEZEx/PFv0Wm0+DrHRKNg6E+fXET1/LFoFm5WselGFzGJENxMMq\nXFbswijxjMrtY5c1BHYeOTC0srzzc2hRYQKQjbxv0ILnvgHu5FkxACC+VwARAQAB\nzRBQb29yTWFuSGFuZHNoYWtlwsGGBBMBCgAwBQJkm28LAhsGAwsJDQMVCggEFgMB\nAAIeARYhBMJQOYV/vWoFW7h4vGjN6M/9cJyqAAoJEGjN6M/9cJyqlCIP/3huUDX+\n8sZNcp1UvAzdc+VZIuzVNZ/IBLpzw1xxhneVIVhjFIkZblmjvmuncgnVzXtNqjdj\nrkPNdSzW4hEOqzkxgz2AKrxNuvcxlhcr11OvxoMqukGx5oMoEAjoDdGxE2680o0P\nOioC3P9TXT+7BvjVsXojf8oUAyBzu3DQZiLiqTLEOH/BlYNW3uDnPPKEqeZPTv9e\n/NbLL4cSj360pztmO4OhJzqb1sgLutFfn89ctFZoHfcFLlSV2PM1Biw3DXzCn+im\nsUj3YaGDKkpImpZS01Q1+65IBxbQkKKNBhbwsGWLChRy6bQsTli4/l8KDLqqfW2W\nX3phYeb4+PvjoKY7ERnc8OLFB6nuUACglt7G4EIErCskI/VYXJvHeARNHiLsWp5K\n2NtOvpRgMy+17HMia+7kMFuY1mDOSpu2yLDq/z8aRiZO4vCbab7fJvhdX6kaBFKR\n3I1vVhGWOl+pGVvbr7Thrp9Nr92B6q8CxaUym996VnOLNH7Sk4xC9721HCCP6O0p\nIiLb8reakbKil4T6ymZysz80NECjF8TZCZqnP3+nBGqeLYSrd73mOmcDs9oHBZBx\nSklQ1Xl4tzE24IEksakwvGWZ/CYiD1WILW8JyNfUNeso95Gnu+Mc7Zv1EsdtGK0X\n7l4nKHgW+YW4jgqcrfxpij6dWz92VMvwJ3kX\n=NiKb\n-----END PGP PUBLIC KEY BLOCK-----\n', 'peer': 'VoiceSatelliteV0.3.0:192.168.100.245::461a1391-88b9-49ca-9ee9-c12f2624d540', 'node_id': 'master:0.0.0.0'}
2023-06-27 19:25:04.996 - OVOS - hivemind_bus_client.client:on_message:148 - WARNING - Message was unencrypted
2023-06-27 19:25:05.006 - OVOS - hivemind_bus_client.protocol:handle_handshake:130 - INFO - HANDSHAKE: {'handshake': False, 'min_protocol_version': 0, 'max_protocol_version': 1, 'preshared_key': True, 'password': True, 'crypto_required': True}
2023-06-27 19:25:05.015 - OVOS - hivemind_bus_client.client:emit:186 - INFO - sending to HiveMind: {"msg_type": "shake", "payload": {"envelope": "7666347a6576783002e471d1bc8256a39114a59b68553bad"}, "route": [], "node": null, "source_peer": null}
2023-06-27 19:25:05.041 - OVOS - ovos_bus_client.client.client:on_error:108 - WARNING - Could not send message because connection has closed
2023-06-27 19:25:05.046 - OVOS - ovos_bus_client.client.client:on_error:119 - ERROR - Exception closing websocket at ws://192.168.100.55:5678?authorization=Vm9pY2VTYXRlbGxpdGVWMC4zLjA6MzcyNTdlNWVkMDhkNTg2MDA5NDM0ZGQ4N2I0ODIwMTM=: Connection is already closed.
2023-06-27 19:25:05.056 - OVOS - ovos_bus_client.client.client:on_error:121 - WARNING - Message Bus Client will reconnect in 5.0 seconds.
2023-06-27 19:25:10.164 - OVOS - hivemind_bus_client.client:on_message:148 - WARNING - Message was unencrypted
2023-06-27 19:25:10.172 - OVOS - hivemind_bus_client.protocol:handle_hello:122 - INFO - HELLO: {'pubkey': '-----BEGIN PGP PUBLIC KEY BLOCK-----\n\nxsFNBGSbbwoBEAC0k5PzsGEizC1bRZOE/PstNmnBjZNwvaof8uoijVFZbWwMJzPo\nu+jkLbSW42ejOV3tB97v/mJ8f+yZ0ep/GzwTpjF/JYg+WyCACV1S5Vm2eGHMrCeP\nvVUyjS3U1JjQbK7nisyu6/mPyUMt6bAnc77H7PHBnQTOAcqB5o9BDNoXwSiIdNHR\nS1f3XlZKZiW5fzFoNzj/3t9OIrEI59xHMaLwQJ5tObPi5PDxZTBEWICBPA3Uu1Nu\nrGSCpWvC5pxKeSUEJMmGhioITTe2D7CMQYO2tffoiVYQ3OIzyABahaeSz9xYl0Ot\n4IGWVO1fQzQBP7Pse04YADf+e7fjaqguiFySB3nkFh08U/2hOiAECykqwXW7NEzt\n4Vkhwa446AwJFIKX9vvtJHlGrnyQvayCAJ59MpO9vexpq9Vf+uRTbYEG0zJtqFRY\n25jgF9R+RcLoq0qNfS6pAzkf17IZ2MSXuCn9h4vEpMhGSxKjT+n///5ltnsMGkQ2\nUmext84qMAfgvRqSqJSNnhmhuCxRPqmSa+0lyZymuLJtfzX22cSuuXAKbfTr9Is5\nwmfrSvofyUiQckEZEx/PFv0Wm0+DrHRKNg6E+fXET1/LFoFm5WselGFzGJENxMMq\nXFbswijxjMrtY5c1BHYeOTC0srzzc2hRYQKQjbxv0ILnvgHu5FkxACC+VwARAQAB\nzRBQb29yTWFuSGFuZHNoYWtlwsGGBBMBCgAwBQJkm28LAhsGAwsJDQMVCggEFgMB\nAAIeARYhBMJQOYV/vWoFW7h4vGjN6M/9cJyqAAoJEGjN6M/9cJyqlCIP/3huUDX+\n8sZNcp1UvAzdc+VZIuzVNZ/IBLpzw1xxhneVIVhjFIkZblmjvmuncgnVzXtNqjdj\nrkPNdSzW4hEOqzkxgz2AKrxNuvcxlhcr11OvxoMqukGx5oMoEAjoDdGxE2680o0P\nOioC3P9TXT+7BvjVsXojf8oUAyBzu3DQZiLiqTLEOH/BlYNW3uDnPPKEqeZPTv9e\n/NbLL4cSj360pztmO4OhJzqb1sgLutFfn89ctFZoHfcFLlSV2PM1Biw3DXzCn+im\nsUj3YaGDKkpImpZS01Q1+65IBxbQkKKNBhbwsGWLChRy6bQsTli4/l8KDLqqfW2W\nX3phYeb4+PvjoKY7ERnc8OLFB6nuUACglt7G4EIErCskI/VYXJvHeARNHiLsWp5K\n2NtOvpRgMy+17HMia+7kMFuY1mDOSpu2yLDq/z8aRiZO4vCbab7fJvhdX6kaBFKR\n3I1vVhGWOl+pGVvbr7Thrp9Nr92B6q8CxaUym996VnOLNH7Sk4xC9721HCCP6O0p\nIiLb8reakbKil4T6ymZysz80NECjF8TZCZqnP3+nBGqeLYSrd73mOmcDs9oHBZBx\nSklQ1Xl4tzE24IEksakwvGWZ/CYiD1WILW8JyNfUNeso95Gnu+Mc7Zv1EsdtGK0X\n7l4nKHgW+YW4jgqcrfxpij6dWz92VMvwJ3kX\n=NiKb\n-----END PGP PUBLIC KEY BLOCK-----\n', 'peer': 'VoiceSatelliteV0.3.0:192.168.100.245::ba5d7c52-1cac-4813-a183-f65a39edf1dc', 'node_id': 'master:0.0.0.0'}
2023-06-27 19:25:10.181 - OVOS - hivemind_bus_client.client:on_message:148 - WARNING - Message was unencrypted
2023-06-27 19:25:10.187 - OVOS - hivemind_bus_client.protocol:handle_handshake:130 - INFO - HANDSHAKE: {'handshake': False, 'min_protocol_version': 0, 'max_protocol_version': 1, 'preshared_key': True, 'password': True, 'crypto_required': True}
2023-06-27 19:25:10.194 - OVOS - hivemind_bus_client.client:emit:186 - INFO - sending to HiveMind: {"msg_type": "shake", "payload": {"envelope": "464f7459366774732fc4968babaf4280c462a3ad5469d5ae"}, "route": [], "node": null, "source_peer": null}
2023-06-27 19:25:10.216 - OVOS - ovos_bus_client.client.client:on_error:108 - WARNING - Could not send message because connection has closed
2023-06-27 19:25:10.223 - OVOS - ovos_bus_client.client.client:on_error:119 - ERROR - Exception closing websocket at ws://192.168.100.55:5678?authorization=Vm9pY2VTYXRlbGxpdGVWMC4zLjA6MzcyNTdlNWVkMDhkNTg2MDA5NDM0ZGQ4N2I0ODIwMTM=: Connection is already closed.
2023-06-27 19:25:10.229 - OVOS - ovos_bus_client.client.client:on_error:121 - WARNING - Message Bus Client will reconnect in 5.0 seconds.
```

Logs from the listener
```
2023-06-27 23:25:15.254 - HiveMind - hivemind_core.service:open:124 - INFO - authorizing client: VoiceSatelliteV0.3.0
2023-06-27 23:25:15.286 - HiveMind - hivemind_core.protocol:handle_new_client:224 - INFO - new client: VoiceSatelliteV0.3.0:192.168.100.245::7b89089c-44e2-4f0e-b1a8-f215446c9637
2023-06-27 23:25:15.310 - HiveMind - hivemind_core.protocol:handle_new_client:239 - INFO - saying HELLO to: VoiceSatelliteV0.3.0:192.168.100.245::7b89089c-44e2-4f0e-b1a8-f215446c9637
2023-06-27 23:25:15.322 - HiveMind - hivemind_core.protocol:send:76 - INFO - sending to VoiceSatelliteV0.3.0:192.168.100.245::7b89089c-44e2-4f0e-b1a8-f215446c9637: {"msg_type": "hello", "payload": {"pubkey": "-----BEGIN PGP PUBLIC KEY BLOCK-----\n\nxsFNBGSbbwoBEAC0k5PzsGEizC1bRZOE/PstNmnBjZNwvaof8uoijVFZbWwMJzPo\nu+jkLbSW42ejOV3tB97v/mJ8f+yZ0ep/GzwTpjF/JYg+WyCACV1S5Vm2eGHMrCeP\nvVUyjS3U1JjQbK7nisyu6/mPyUMt6bAnc77H7PHBnQTOAcqB5o9BDNoXwSiIdNHR\nS1f3XlZKZiW5fzFoNzj/3t9OIrEI59xHMaLwQJ5tObPi5PDxZTBEWICBPA3Uu1Nu\nrGSCpWvC5pxKeSUEJMmGhioITTe2D7CMQYO2tffoiVYQ3OIzyABahaeSz9xYl0Ot\n4IGWVO1fQzQBP7Pse04YADf+e7fjaqguiFySB3nkFh08U/2hOiAECykqwXW7NEzt\n4Vkhwa446AwJFIKX9vvtJHlGrnyQvayCAJ59MpO9vexpq9Vf+uRTbYEG0zJtqFRY\n25jgF9R+RcLoq0qNfS6pAzkf17IZ2MSXuCn9h4vEpMhGSxKjT+n///5ltnsMGkQ2\nUmext84qMAfgvRqSqJSNnhmhuCxRPqmSa+0lyZymuLJtfzX22cSuuXAKbfTr9Is5\nwmfrSvofyUiQckEZEx/PFv0Wm0+DrHRKNg6E+fXET1/LFoFm5WselGFzGJENxMMq\nXFbswijxjMrtY5c1BHYeOTC0srzzc2hRYQKQjbxv0ILnvgHu5FkxACC+VwARAQAB\nzRBQb29yTWFuSGFuZHNoYWtlwsGGBBMBCgAwBQJkm28LAhsGAwsJDQMVCggEFgMB\nAAIeARYhBMJQOYV/vWoFW7h4vGjN6M/9cJyqAAoJEGjN6M/9cJyqlCIP/3huUDX+\n8sZNcp1UvAzdc+VZIuzVNZ/IBLpzw1xxhneVIVhjFIkZblmjvmuncgnVzXtNqjdj\nrkPNdSzW4hEOqzkxgz2AKrxNuvcxlhcr11OvxoMqukGx5oMoEAjoDdGxE2680o0P\nOioC3P9TXT+7BvjVsXojf8oUAyBzu3DQZiLiqTLEOH/BlYNW3uDnPPKEqeZPTv9e\n/NbLL4cSj360pztmO4OhJzqb1sgLutFfn89ctFZoHfcFLlSV2PM1Biw3DXzCn+im\nsUj3YaGDKkpImpZS01Q1+65IBxbQkKKNBhbwsGWLChRy6bQsTli4/l8KDLqqfW2W\nX3phYeb4+PvjoKY7ERnc8OLFB6nuUACglt7G4EIErCskI/VYXJvHeARNHiLsWp5K\n2NtOvpRgMy+17HMia+7kMFuY1mDOSpu2yLDq/z8aRiZO4vCbab7fJvhdX6kaBFKR\n3I1vVhGWOl+pGVvbr7Thrp9Nr92B6q8CxaUym996VnOLNH7Sk4xC9721HCCP6O0p\nIiLb8reakbKil4T6ymZysz80NECjF8TZCZqnP3+nBGqeLYSrd73mOmcDs9oHBZBx\nSklQ1Xl4tzE24IEksakwvGWZ/CYiD1WILW8JyNfUNeso95Gnu+Mc7Zv1EsdtGK0X\n7l4nKHgW+YW4jgqcrfxpij6dWz92VMvwJ3kX\n=NiKb\n-----END PGP PUBLIC KEY BLOCK-----\n", "peer": "VoiceSatelliteV0.3.0:192.168.100.245::7b89089c-44e2-4f0e-b1a8-f215446c9637", "node_id": "master:0.0.0.0"}, "route": [], "node": null, "source_peer": null}
2023-06-27 23:25:15.328 - HiveMind - hivemind_core.protocol:send:83 - WARNING - sent unencrypted!
2023-06-27 23:25:15.342 - HiveMind - hivemind_core.protocol:handle_new_client:254 - INFO - starting VoiceSatelliteV0.3.0:192.168.100.245::7b89089c-44e2-4f0e-b1a8-f215446c9637 HANDSHAKE: {'handshake': False, 'min_protocol_version': <ProtocolVersion.ZERO: 0>, 'max_protocol_version': <ProtocolVersion.ONE: 1>, 'preshared_key': True, 'password': True, 'crypto_required': True}
2023-06-27 23:25:15.350 - HiveMind - hivemind_core.protocol:send:76 - INFO - sending to VoiceSatelliteV0.3.0:192.168.100.245::7b89089c-44e2-4f0e-b1a8-f215446c9637: {"msg_type": "shake", "payload": {"handshake": false, "min_protocol_version": 0, "max_protocol_version": 1, "preshared_key": true, "password": true, "crypto_required": true}, "route": [], "node": null, "source_peer": null}
2023-06-27 23:25:15.358 - HiveMind - hivemind_core.protocol:send:83 - WARNING - sent unencrypted!
2023-06-27 23:25:15.397 - HiveMind - ovos_utils.security:decrypt:101 - ERROR - decryption failed, invalid key?
Uncaught exception GET /?authorization=Vm9pY2VTYXRlbGxpdGVWMC4zLjA6MzcyNTdlNWVkMDhkNTg2MDA5NDM0ZGQ4N2I0ODIwMTM= (192.168.100.245)
HTTPServerRequest(protocol='http', host='192.168.100.55:5678', method='GET', uri='/?authorization=Vm9pY2VTYXRlbGxpdGVWMC4zLjA6MzcyNTdlNWVkMDhkNTg2MDA5NDM0ZGQ4N2I0ODIwMTM=', version='HTTP/1.1', remote_ip='192.168.100.245')
Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/hivemind_bus_client/util.py", line 126, in decrypt_from_json
    return decrypt(key, ciphertext, tag, nonce)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_utils/security.py", line 97, in decrypt
    data = cipher.decrypt_and_verify(ciphertext, tag)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/Cryptodome/Cipher/_mode_gcm.py", line 567, in decrypt_and_verify
    self.verify(received_mac_tag)
  File "/home/ovos/.venv/lib/python3.11/site-packages/Cryptodome/Cipher/_mode_gcm.py", line 508, in verify
    raise ValueError("MAC check failed")
ValueError: MAC check failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/tornado/websocket.py", line 630, in _run_callback
    result = callback(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/hivemind_core/service.py", line 117, in on_message
    message = self.client.decode(message)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/hivemind_core/protocol.py", line 91, in decode
    payload = decrypt_from_json(self.crypto_key, payload)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/hivemind_bus_client/util.py", line 128, in decrypt_from_json
    raise DecryptionKeyError
hivemind_bus_client.exceptions.DecryptionKeyError

```

**Comment by goldyfruit** [comment]
Duplicate https://github.com/JarbasHiveMind/HiveMind-core/issues/78
