### ISSUE TITLE
TypeError: HiveMessage.__init__() got an unexpected keyword argument 'ciphertext'

### ISSUE THREAD

**Issue by goldyfruit** [JarbasHiveMind/HiveMind-voice-sat#25]
Logs from the `listener`:

```
ovos-core-8686984476-8xj2f ovos-hivemind-listener 2023-09-03 14:20:35.354 - HiveMind - hivemind_core.protocol:decode:103 - WARNING - Message was unencrypted
ovos-core-8686984476-8xj2f ovos-hivemind-listener 2023-09-03 14:20:35.361 - HiveMind - hivemind_core.service:on_message:114 - INFO - received VoiceSatelliteV0.3.0:10.233.75.0::0e0826ea-3d09-41b9-9e9c-2d8dbeecfd92 message: {"msg_type": "bus", "payload": {"type": "recognizer_loop:wakeword", "data": {"engine": "PreciseLiteHotwordPlugin", "sound": null, "bus_event": null, "trigger": false, "utterance": "hey mycroft", "stt_lang": "en-us", "listen": true, "wakeup": false, "stopword": false, "key_phrase": "hey_mycroft", "module": "ovos-ww-plugin-precise-lite"}, "context": {"client_name": "ovos_dinkum_listener", "source": "audio", "destination": ["skills"]}}, "route": [], "node": null, "source_peer": null}
ovos-core-8686984476-8xj2f ovos-hivemind-listener 2023-09-03 14:20:35.377 - HiveMind - hivemind_core.protocol:handle_inject_mycroft_msg:481 - WARNING - VoiceSatelliteV0.3.0:10.233.75.0::0e0826ea-3d09-41b9-9e9c-2d8dbeecfd92 sent an unauthorized bus message
ovos-core-8686984476-8xj2f ovos-hivemind-listener 2023-09-03 14:20:35.387 - HiveMind - hivemind_core.protocol:decode:103 - WARNING - Message was unencrypted
ovos-core-8686984476-8xj2f ovos-hivemind-listener 2023-09-03 14:20:35.397 - HiveMind - hivemind_core.service:on_message:114 - INFO - received VoiceSatelliteV0.3.0:10.233.75.0::0e0826ea-3d09-41b9-9e9c-2d8dbeecfd92 message: {"msg_type": "bus", "payload": {"type": "recognizer_loop:record_begin", "data": {}, "context": {}}, "route": [], "node": null, "source_peer": null}
ovos-core-8686984476-8xj2f ovos-hivemind-listener 2023-09-03 14:20:35.413 - HiveMind - hivemind_core.protocol:handle_inject_mycroft_msg:481 - WARNING - VoiceSatelliteV0.3.0:10.233.75.0::0e0826ea-3d09-41b9-9e9c-2d8dbeecfd92 sent an unauthorized bus message
ovos-core-8686984476-8xj2f ovos-hivemind-listener 2023-09-03 14:20:37.671 - HiveMind - hivemind_core.protocol:decode:103 - WARNING - Message was unencrypted
ovos-core-8686984476-8xj2f ovos-hivemind-listener 2023-09-03 14:20:37.678 - HiveMind - hivemind_core.service:on_message:114 - INFO - received VoiceSatelliteV0.3.0:10.233.75.0::0e0826ea-3d09-41b9-9e9c-2d8dbeecfd92 message: {"msg_type": "bus", "payload": {"type": "recognizer_loop:record_end", "data": {}, "context": {"client_name": "ovos_dinkum_listener", "source": "audio", "destination": ["skills"], "transcription": "\"What time is it?\""}}, "route": [], "node": null, "source_peer": null}
ovos-core-8686984476-8xj2f ovos-hivemind-listener 2023-09-03 14:20:37.689 - HiveMind - hivemind_core.protocol:handle_inject_mycroft_msg:481 - WARNING - VoiceSatelliteV0.3.0:10.233.75.0::0e0826ea-3d09-41b9-9e9c-2d8dbeecfd92 sent an unauthorized bus message
ovos-core-8686984476-8xj2f ovos-hivemind-listener 2023-09-03 14:20:37.695 - HiveMind - hivemind_core.protocol:decode:103 - WARNING - Message was unencrypted
ovos-core-8686984476-8xj2f ovos-hivemind-listener 2023-09-03 14:20:37.702 - HiveMind - hivemind_core.service:on_message:114 - INFO - received VoiceSatelliteV0.3.0:10.233.75.0::0e0826ea-3d09-41b9-9e9c-2d8dbeecfd92 message: {"msg_type": "bus", "payload": {"type": "recognizer_loop:utterance", "data": {"client_name": "ovos_dinkum_listener", "source": "audio", "destination": ["skills"], "transcription": "\"What time is it?\"", "utterances": ["\"What time is it?\""]}, "context": {"client_name": "ovos_dinkum_listener", "source": "audio", "destination": ["skills"], "transcription": "\"What time is it?\"", "utterances": ["\"What time is it?\""]}}, "route": [], "node": null, "source_peer": null}
ovos-core-8686984476-8xj2f ovos-hivemind-listener 2023-09-03 14:20:37.714 - HiveMind - hivemind_core.protocol:handle_inject_mycroft_msg:492 - INFO - Forwarding message to mycroft bus from client: VoiceSatelliteV0.3.0:10.233.75.0::0e0826ea-3d09-41b9-9e9c-2d8dbeecfd92
```

Logs fro `voice-sat`:

```
2023-09-03 10:20:35.346 - OVOS - ovos_dinkum_listener.voice_loop.voice_loop:run:205 - INFO - Wakeword detected
2023-09-03 10:20:37.189 - OVOS - ovos_dinkum_listener.voice_loop.voice_loop:run:235 - INFO - speech finished
2023-09-03 10:20:37.649 - OVOS - ovos_dinkum_listener.voice_loop.voice_loop:_after_cmd:640 - INFO - transcribed: "What time is it?"
2023-09-03 10:20:37.975 - OVOS - ovos_bus_client.client.client:on_error:112 - ERROR - === TypeError("HiveMessage.__init__() got an unexpected keyword argument 'ciphertext'") ===
Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_socket.py", line 108, in recv
    bytes_ = _recv()
             ^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_socket.py", line 87, in _recv
    return sock.recv(bufsize)
           ^^^^^^^^^^^^^^^^^^
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_bus_client/client/client.py", line 115, in on_error
    self.emitter.emit('error', error)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_base.py", line 118, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_base.py", line 88, in _emit_handle_potential_error
    raise error
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_app.py", line 434, in setSock
    dispatcher.read(self.sock.sock, read, check)
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_app.py", line 80, in read
    if not read_callback():
           ^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_app.py", line 443, in read
    op_code, frame = self.sock.recv_data_frame(True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_core.py", line 406, in recv_data_frame
    frame = self.recv_frame()
            ^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_core.py", line 445, in recv_frame
    return self.frame_buffer.recv_frame()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_abnf.py", line 338, in recv_frame
    self.recv_header()
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_abnf.py", line 294, in recv_header
    header = self.recv_strict(2)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_abnf.py", line 373, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_core.py", line 529, in _recv
    return recv(self.sock, bufsize)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_socket.py", line 110, in recv
    raise WebSocketTimeoutException("Connection timed out")
websocket._exceptions.WebSocketTimeoutException: Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_bus_client/client/client.py", line 115, in on_error
    self.emitter.emit('error', error)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_base.py", line 118, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_base.py", line 88, in _emit_handle_potential_error
    raise error
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_app.py", line 418, in setSock
    self.sock.connect(
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_core.py", line 249, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_http.py", line 129, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_http.py", line 196, in _open_socket
    raise error
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_http.py", line 184, in _open_socket
    sock.connect(address)
OSError: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_bus_client/client/client.py", line 115, in on_error
    self.emitter.emit('error', error)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_base.py", line 118, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_base.py", line 88, in _emit_handle_potential_error
    raise error
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_app.py", line 418, in setSock
    self.sock.connect(
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_core.py", line 249, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_http.py", line 129, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_http.py", line 196, in _open_socket
    raise error
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_http.py", line 184, in _open_socket
    sock.connect(address)
OSError: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_bus_client/client/client.py", line 115, in on_error
    self.emitter.emit('error', error)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_base.py", line 118, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_base.py", line 88, in _emit_handle_potential_error
    raise error
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_app.py", line 418, in setSock
    self.sock.connect(
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_core.py", line 249, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_http.py", line 129, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_http.py", line 196, in _open_socket
    raise error
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_http.py", line 184, in _open_socket
    sock.connect(address)
OSError: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_bus_client/client/client.py", line 115, in on_error
    self.emitter.emit('error', error)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_base.py", line 118, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_base.py", line 88, in _emit_handle_potential_error
    raise error
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_app.py", line 418, in setSock
    self.sock.connect(
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_core.py", line 249, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_http.py", line 129, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_http.py", line 196, in _open_socket
    raise error
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_http.py", line 184, in _open_socket
    sock.connect(address)
OSError: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_bus_client/client/client.py", line 115, in on_error
    self.emitter.emit('error', error)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_base.py", line 118, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_base.py", line 88, in _emit_handle_potential_error
    raise error
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_app.py", line 418, in setSock
    self.sock.connect(
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_core.py", line 249, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_http.py", line 129, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_http.py", line 196, in _open_socket
    raise error
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_http.py", line 184, in _open_socket
    sock.connect(address)
OSError: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_bus_client/client/client.py", line 115, in on_error
    self.emitter.emit('error', error)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_base.py", line 118, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_base.py", line 88, in _emit_handle_potential_error
    raise error
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_app.py", line 553, in _callback
    callback(self, *args)
  File "/home/ovos/.venv/lib/python3.11/site-packages/hivemind_bus_client/client.py", line 186, in on_message
    self._handle_hive_protocol(HiveMessage(**message))
                               ^^^^^^^^^^^^^^^^^^^^^^
TypeError: HiveMessage.__init__() got an unexpected keyword argument 'ciphertext'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_bus_client/client/client.py", line 115, in on_error
    self.emitter.emit('error', error)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_base.py", line 118, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_base.py", line 88, in _emit_handle_potential_error
    raise error
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_app.py", line 553, in _callback
    callback(self, *args)
  File "/home/ovos/.venv/lib/python3.11/site-packages/hivemind_bus_client/client.py", line 186, in on_message
    self._handle_hive_protocol(HiveMessage(**message))
                               ^^^^^^^^^^^^^^^^^^^^^^
TypeError: HiveMessage.__init__() got an unexpected keyword argument 'ciphertext'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_bus_client/client/client.py", line 115, in on_error
    self.emitter.emit('error', error)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_base.py", line 118, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_base.py", line 88, in _emit_handle_potential_error
    raise error
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_app.py", line 553, in _callback
    callback(self, *args)
  File "/home/ovos/.venv/lib/python3.11/site-packages/hivemind_bus_client/client.py", line 186, in on_message
    self._handle_hive_protocol(HiveMessage(**message))
                               ^^^^^^^^^^^^^^^^^^^^^^
TypeError: HiveMessage.__init__() got an unexpected keyword argument 'ciphertext'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_app.py", line 553, in _callback
    callback(self, *args)
  File "/home/ovos/.venv/lib/python3.11/site-packages/hivemind_bus_client/client.py", line 186, in on_message
    self._handle_hive_protocol(HiveMessage(**message))
                               ^^^^^^^^^^^^^^^^^^^^^^
TypeError: HiveMessage.__init__() got an unexpected keyword argument 'ciphertext'
2023-09-03 10:20:38.052 - OVOS - ovos_bus_client.client.client:on_error:119 - ERROR - Exception closing websocket at ws://192.168.100.55:5678?authorization=Vm9pY2VTYXRlbGxpdGVWMC4zLjA6OTViNzc0ZjFlODVjMmVhOGU4YTgwYWMyYzVkMDljNmI=: HiveMessage.__init__() got an unexpected keyword argument 'ciphertext'
2023-09-03 10:20:38.085 - OVOS - ovos_bus_client.client.client:on_error:121 - WARNING - Message Bus Client will reconnect in 5.0 seconds.
```

**Comment by Ramblurr** [comment]
@builderjer posted this in the HM Suppoert matrix room as a workaround:

![image](https://github.com/JarbasHiveMind/HiveMind-voice-sat/assets/14830/b4aa1f32-e18c-42e0-aeb7-c7aa92b26dde)

**Comment by JarbasAl** [comment]
fixed in https://github.com/JarbasHiveMind/hivemind_websocket_client/commit/31af417251103069d26d924c7d9fe6819b386bf5
